- name: Create Config file
  ansible.builtin.template:
    src: s-job.xml
    dest: /tmp/s-m-job.xml
  vars:
    item_name: lookup('community.general.random_string', special=false, upper=false, length=12)

- name: Create Job
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/m-job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.2.245:8080
    user: admin
    password: "{{jenkins_password}}"
